name: push container image

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: downcase REPO
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
    - uses: actions/checkout@v3
    - name: build and push
      run: |
        IMAGE_NAME=sample_image:${GITHUB_REF#refs/heads/}
        docker build -t ghcr.io/${REPO}/${IMAGE_NAME} .
        echo ${CR_PAT} | docker login ghcr.io -u oyuyo --password-stdin
        docker push ghcr.io/${REPO}/${IMAGE_NAME}
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
